<a href="https://colab.research.google.com/github/sngo/learnpytorch/blob/main/00_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

tensor7 = torch.rand(7, 7)
tensor7

tensor([[0.8131, 0.3820, 0.0510, 0.0160, 0.9875, 0.3360, 0.3210],
        [0.4310, 0.9372, 0.7293, 0.9585, 0.3628, 0.6963, 0.8345],
        [0.7548, 0.2612, 0.5058, 0.1214, 0.9945, 0.6270, 0.5105],
        [0.6405, 0.3229, 0.8017, 0.4314, 0.9498, 0.0125, 0.5599],
        [0.2495, 0.9196, 0.8744, 0.1483, 0.3728, 0.3450, 0.6665],
        [0.7354, 0.1531, 0.3226, 0.5989, 0.2555, 0.5218, 0.5652],
        [0.0606, 0.9382, 0.4969, 0.3926, 0.0157, 0.4576, 0.1632]])

In [ ]:
tensor72 = torch.rand(1,7)
tensor72

tensor([[0.7867, 0.8915, 0.7252, 0.6108, 0.0610, 0.7603, 0.3829]])

In [ ]:
tensor72.T

tensor([[0.7867],
        [0.8915],
        [0.7252],
        [0.6108],
        [0.0610],
        [0.7603],
        [0.3829]])

In [ ]:
tensor_mul = tensor7.mul(tensor72.T)
tensor_mul

tensor([[0.6397, 0.3005, 0.0401, 0.0126, 0.7769, 0.2643, 0.2525],
        [0.3842, 0.8355, 0.6502, 0.8545, 0.3234, 0.6208, 0.7440],
        [0.5474, 0.1894, 0.3669, 0.0880, 0.7213, 0.4547, 0.3702],
        [0.3912, 0.1973, 0.4897, 0.2635, 0.5801, 0.0076, 0.3420],
        [0.0152, 0.0561, 0.0533, 0.0090, 0.0227, 0.0210, 0.0407],
        [0.5591, 0.1164, 0.2452, 0.4553, 0.1943, 0.3967, 0.4297],
        [0.0232, 0.3592, 0.1903, 0.1503, 0.0060, 0.1752, 0.0625]])

In [ ]:
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)
tensor55 = torch.rand(5,5)
torch.manual_seed(seed=RANDOM_SEED)
tensor15 = torch.rand(1,5)
tensor55, tensor15

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074],
         [0.6341, 0.4901, 0.8964, 0.4556, 0.6323],
         [0.3489, 0.4017, 0.0223, 0.1689, 0.2939],
         [0.5185, 0.6977, 0.8000, 0.1610, 0.2823],
         [0.6816, 0.9152, 0.3971, 0.8742, 0.4194]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074]]))

In [ ]:
tensor23_1 = torch.rand(2,3)
tensor23_2 = torch.rand(2,3)
#multensor = tensor23_1.mul(tensor23_2.T)
tensor23_1, tensor23_2,tensor23_1.ndim, tensor23_1.shape, tensor23_2.ndim, tensor23_2.shape

(tensor([[0.3734, 0.3051, 0.9320],
         [0.1759, 0.2698, 0.1507]]),
 tensor([[0.0317, 0.2081, 0.9298],
         [0.7231, 0.7423, 0.5263]]),
 2,
 torch.Size([2, 3]),
 2,
 torch.Size([2, 3]))

In [ ]:

multensor = tensor23_1.mul(tensor23_2)
tensor23_2.T, multensor

(tensor([[0.0317, 0.7231],
         [0.2081, 0.7423],
         [0.9298, 0.5263]]),
 tensor([[0.0118, 0.0635, 0.8666],
         [0.1272, 0.2003, 0.0793]]))

In [ ]:
max = multensor.max()
min = multensor.min()
max, min

(tensor(0.8666), tensor(0.0118))

In [ ]:
rtensor = torch.rand(1,1,1, 10)
rtensor

tensor([[[[0.9971, 0.6984, 0.5675, 0.8352, 0.2056, 0.5932, 0.1123, 0.1535,
           0.2417, 0.7262]]]])

In [ ]:
ones = torch.ones_like(rtensor)
ones

tensor([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]]])

In [ ]:
from math import sqrt
SEED = 7
torch.manual_seed = SEED
squeeze = rtensor.squeeze()
squeeze


tensor([0.9971, 0.6984, 0.5675, 0.8352, 0.2056, 0.5932, 0.1123, 0.1535, 0.2417,
        0.7262])